#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: PAAL - Turkey and Tech!
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  PAAL “Preparing Adolescents with Autism for Adult Life” began operations in September of 2006.  PAAL is a specialty secondary-educational program for adolescents with moderate to severe autism between the ages of 14 and 21, which establishes a professional collaboration between the educational system, families, and the community-at-large.  The primary goal of the PAAL program is to identify and teach the skills which must be mastered to prepare the student for his or her post-21 years.  Since “best practices’ indicate that individuals with autism learn better in the naturally-occurring environment, the program utilizes the community as its classroom.  By so doing, the fundamental principles of transition and integration into the community for adult life are supported.
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Mission for Educating Citizens with Autism (MECA) assists individuals with autism in reaching their full potential as productive, socially-connected, and personally-fulfilled individuals by establishing appropriate educational in the least restrictive environment possible, by raising the general public’s awareness of autism, by advocating for greater acceptance and support of individuals with autism, and by facilitating opportunities for persons with autism to participate more fully in their communities.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: jcummings@paalprogram.org
org_street_address: 1355 Market Street #Please include suite number on the line below
org_address_suite: Suite 900
org_city: San Francisco
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  94103
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (123) 456-7890

#SOCIAL MEDIA
org_twitter_username: smartergiving
org_facebook_username: smartergiving
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
